name: inglo
description: "2024 solution challenge inglo"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

#모바일에 표시될 앱이름
flutter_launcher_name:
  name: "inglo"

dependencies:
  flutter:
    sdk: flutter
  # 2024 2 3 기준 version
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  flutter_svg: ^2.0.9 # svg icon으로 사용
  flutter_svg_provider: ^1.0.7 # svg backgorund image로 사용
  google_maps_flutter: ^2.5.3
  google_maps_flutter_web: ^0.5.4+3
  flutter_dotenv: ^5.1.0
  flutter_config: ^2.0.2
  dropdown_button2: ^2.3.9
  modal_bottom_sheet: ^3.0.0-pre
  webview_flutter: ^3.0.4
  google_fonts: ^6.1.0
  flutter_staggered_grid_view: ^0.7.0
  scribble: ^0.9.1
  flutter_state_notifier: ^0.7.1
  html_editor_enhanced: ^2.5.1
  comment_box: ^0.0.18
  syncfusion_flutter_gauges: ^24.2.6
  flutter_localization: ^0.2.0
  syncfusion_localizations: ^24.2.6
  flutter_profile_picture: ^2.0.0
  image_picker: ^1.0.7
  vertical_card_pager: ^1.4.0
  google_sign_in: ^6.2.1
  pager: ^0.0.6
  http: ^1.2.0
  google_sign_in_android: ^6.1.21
  dio: ^5.4.1
  flutter_provider: ^2.1.0
  url_launcher: ^6.2.4
  flutter_secure_storage: ^9.0.0
  path_provider: ^2.1.2
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon/navigation/
    - assets/image/background/
    - assets/image/design/
    - assets/image/home/
    - assets/image/sdgs/
    - .env
    - assets/image/
    - assets/image/slider/
    - assets/image/logo/