List<String> sdgsData = [
  'no poverty',
  'zero hunger',
  'good health and well-being',
  'quality education',
  'gender equality',
  'clean water and sanitation',
  'affordable and clean energy',
  'decent work and economic growth',
  'industry innovation and infrastructure',
  'reduced inequalities',
  'sustainable cities and communities',
  'responsible consumption and production',
  'climate action',
  'life below water',
  'life on land',
  'peace, justice and strong institutions',
  'partnerships for the goals',
];