List<Map<String, String>> sdgsData = [
  {'key': '0', 'value': 'no poverty'},
  {'key': '1', 'value': 'zero hunger'},
  {'key': '2', 'value': 'good health and well-being'},
  {'key': '3', 'value': 'quality education'},
  {'key': '4', 'value': 'gender equality'},
  {'key': '5', 'value': 'clean water and sanitation'},
  {'key': '6', 'value': 'affordable and clean energy'},
  {'key': '7', 'value': 'decent work and economic growth'},
  {'key': '8', 'value': 'industry innovation and infrastructure'},
  {'key': '9', 'value': 'reduced inequalities'},
  {'key': '10', 'value': 'sustainable cities and communities'},
  {'key': '11', 'value': 'responsible consumption and production'},
  {'key': '12', 'value': 'climate action'},
  {'key': '13', 'value': 'life below water'},
  {'key': '14', 'value': 'life on land'},
  {'key': '15', 'value': 'peace, justice and strong institutions'},
  {'key': '16', 'value': 'partnerships for the goals'},
];
