import 'package:inglo/models/post/post_list.dart';

class PostListPreferences {
  static final List<PostList> listItem = [
    PostList(
        id: 1,
        user: 1,
        title: "아주아주아주긴제목이다길면한줄까지만표시가되지롱하하하하하하ㅏㅎ",
        content: "아주아주아주긴내ㅑ용이다 길면두 줄까지만표시가되지롱 하하하하하하ㅏㅎ",
        image_url: "",
        sdgs: 1,
        likes: 0,
        created_at: "2024-02-14T20:51:03.765423Z",
    ),
    PostList(
      id: 1,
      user: 1,
      title: "아주아주아주긴제목이다길면한줄까지만표시가되지롱하하하하하하ㅏㅎ",
      content: "아주아주아주긴내ㅑ용이다 길면두 줄까지만표시가되지롱 하하하하하하ㅏㅎ",
      image_url: "",
      sdgs: 2,
      likes: 7,
      created_at: "2024-02-14T20:51:03.765423Z",
    ),
    PostList(
      id: 1,
      user: 1,
      title: "아주아주아주긴제목이다길면한줄까지만표시가되지롱하하하하하하ㅏㅎ",
      content: "아주아주아주긴내ㅑ용이다 길면두 줄까지만표시가되지롱 하하하하하하ㅏㅎ",
      image_url: "",
      sdgs: 3,
      likes: 67,
      created_at: "2024-02-14T20:51:03.765423Z",
    ),
    PostList(
      id: 1,
      user: 1,
      title: "아주아주아주긴제목이다길면한줄까지만표시가되지롱하하하하하하ㅏㅎ",
      content: "아주아주아주긴내ㅑ용이다 길면두 줄까지만표시가되지롱 하하하하하하ㅏㅎ",
      image_url: "",
      sdgs: 4,
      likes: 4,
      created_at: "2024-02-14T20:51:03.765423Z",
    ),
    PostList(
      id: 1,
      user: 1,
      title: "아주아주아주긴제목이다길면한줄까지만표시가되지롱하하하하하하ㅏㅎ",
      content: "아주아주아주긴내ㅑ용이다 길면두 줄까지만표시가되지롱 하하하하하하ㅏㅎ",
      image_url: "",
      sdgs: 5,
      likes: 42,
      created_at: "2024-02-14T20:51:03.765423Z",
    ),
    PostList(
      id: 1,
      user: 1,
      title: "아주아주아주긴제목이다길면한줄까지만표시가되지롱하하하하하하ㅏㅎ",
      content: "아주아주아주긴내ㅑ용이다 길면두 줄까지만표시가되지롱 하하하하하하ㅏㅎ",
      image_url: "",
      sdgs: 6,
      likes: 0,
      created_at: "2024-02-14T20:51:03.765423Z",
    ),
    PostList(
      id: 1,
      user: 1,
      title: "아주아주아주긴제목이다길면한줄까지만표시가되지롱하하하하하하ㅏㅎ",
      content: "아주아주아주긴내ㅑ용이다 길면두 줄까지만표시가되지롱 하하하하하하ㅏㅎ",
      image_url: "",
      sdgs: 7,
      likes: 33,
      created_at: "2024-02-14T20:51:03.765423Z",
    ),
    PostList(
      id: 1,
      user: 1,
      title: "아주아주아주긴제목이다길면한줄까지만표시가되지롱하하하하하하ㅏㅎ",
      content: "아주아주아주긴내ㅑ용이다 길면두 줄까지만표시가되지롱 하하하하하하ㅏㅎ",
      image_url: "",
      sdgs: 8,
      likes: 2,
      created_at: "2024-02-14T20:51:03.765423Z",
    ),
    PostList(
      id: 1,
      user: 1,
      title: "아주아주아주긴제목이다길면한줄까지만표시가되지롱하하하하하하ㅏㅎ",
      content: "아주아주아주긴내ㅑ용이다 길면두 줄까지만표시가되지롱 하하하하하하ㅏㅎ",
      image_url: "",
      sdgs: 9,
      likes: 9,
      created_at: "2024-02-14T20:51:03.765423Z",
    ),
    PostList(
      id: 1,
      user: 1,
      title: "아주아주아주긴제목이다길면한줄까지만표시가되지롱하하하하하하ㅏㅎ",
      content: "아주아주아주긴내ㅑ용이다 길면두 줄까지만표시가되지롱 하하하하하하ㅏㅎ",
      image_url: "",
      sdgs: 10,
      likes: 7,
      created_at: "2024-02-14T20:51:03.765423Z",
    ),
    PostList(
      id: 1,
      user: 1,
      title: "아주아주아주긴제목이다길면한줄까지만표시가되지롱하하하하하하ㅏㅎ",
      content: "아주아주아주긴내ㅑ용이다 길면두 줄까지만표시가되지롱 하하하하하하ㅏㅎ",
      image_url: "",
      sdgs: 11,
      likes: 5,
      created_at: "2024-02-14T20:51:03.765423Z",
    ),
  ];
}
// 더미데이터
